arm_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint2_to_joint1
    - joint3_to_joint2
    - joint4_to_joint3
    - joint5_to_joint4
    - joint6_to_joint5
    - joint6output_to_joint6
  gains:
    joint2_to_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3_to_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4_to_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5_to_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6_to_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6output_to_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_controller
  gains:
    gripper_controller:
      p: 100
      d: 1
      i: 1
      i_clamp: 1