version: '3.4'

x-app: &common
  command: [ "roslaunch mycobot_ros control_slider.launch" ]
  privileged: true
  environment:
    PYTHONUNBUFFERED: 1
    QT_X11_NO_MITSHM: 1
    DISPLAY: :1
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
  build:
    context: .
    args: &common-args
      ROS_DISTRO: "noetic"
      PYMYCOBOT_VERSION: ">=2<3"
      BASE_IMAGE: nvidia/opengl:1.1-glvnd-runtime-ubuntu20.04


services:
  # This configuration builds the project for computers with NVIDIA hardware
  nvidia-ros: *common

  # This is the default for computers that don't have nvidia hardware accelerators
  ros:
    <<: *common
    build:
      context: .
      args:
        <<: *common-args
        BASE_IMAGE: ubuntu:20.04
