name: industrial_ci

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.jpg'
      - '**.pdf'
      - '**.png'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.jpg'
      - '**.pdf'
      - '**.png'
  schedule:
    - cron: "0 1 * * 2" # Weekly on Tuesdays at 01:00(GMT)

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: melodic, ROS_REPO: main }
          # - { ROS_DISTRO: noetic, ROS_REPO: main }

    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.2.1
        env: ${{ matrix.env }}
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{ matrix.env }}
